rails/rottenpotatoes/config/routes.rb
Rails.application.routes.draw do
  get '/movies', to: 'movies#index'
end

rails/rottenpotatoes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/rottenpotatoes/app/models/movie.rb
class Movie < ActiveRecord::Base
    def self.all_ratings ; %w[G PG PG-13 R] ; end
end

rails/rottenpotatoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/rottenpotatoes/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        @movies = Movie.all
        @ratings = Movie.all_ratings
        @selected_ratings = {"G" => "on"}
        @sorted_by = ""
    end
end

rails/rottenpotatoes/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/rottenpotatoes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rottenpotatoes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

rails/rottenpotatoes/app/views/movies/index.html.erb
<h1>All movies</h1>

<form>
    <input type="hidden" name="sort_by" value="<%= @sort_by %>">
<% @ratings.each do | rating | %>
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="cb_<%= rating %>" <%= @selected_ratings[rating] ? "checked" : "" %> name="selected_ratings[<%= rating %>]" >
        <label class="form-check-label" for="cb_<%= rating %>"><%= rating %></label>
    </div>
<% end %>
    <button type="submit" class="btn btn-outline-primary btn-sm">Apply</button>
</form>

<table class="table table-striped">
  <thead>
    <tr>
      <th class=<%= (@sort_by == "title") ? "table-info" : "" %> >
        <form>
            <input type="hidden" name="sort_by" value="title">
            <% @selected_ratings.each_key do | rating | %>
                <input type="hidden" name="selected_ratings[<%= rating %>]" value="on">
            <% end %>
            <button class="btn btn-link">Movie Title</button>
        </form>
      </th>
      <th>Rating</th>
      <th class=<%= (@sort_by == "release_date") ? "table-info" : "" %> >
        <form>
            <input type="hidden" name="sort_by" value="release_date">
            <% @selected_ratings.each_key do | rating | %>
                <input type="hidden" name="selected_ratings[<%= rating %>]" value="on">
            <% end %>
            <button class="btn btn-link">Release Date</button>
        </form>
      </th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
<% @movies.each do | movie | %>
    <tr>
      <td><%= movie.title %></td>
      <td><%= movie.rating %></td>
      <td><%= movie.release_date %></td>
      <td><%= link_to "More about #{movie.title}", to: movies_path(movie) %></td>
    </tr>
<% end %>
  </tbody>
</table>