phoenix/rottenpotatoes/lib/rottenpotatoes_web/router.ex
defmodule RottenpotatoesWeb.Router do
  use RottenpotatoesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RottenpotatoesWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/movies", MovieController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RottenpotatoesWeb do
  #   pipe_through :api
  # end
end

phoenix/rottenpotatoes/lib/rottenpotatoes/application.ex
defmodule Rottenpotatoes.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Rottenpotatoes.Repo,
      # Start the endpoint when the application starts
      RottenpotatoesWeb.Endpoint
      # Starts a worker by calling: Rottenpotatoes.Worker.start_link(arg)
      # {Rottenpotatoes.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Rottenpotatoes.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    RottenpotatoesWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

phoenix/rottenpotatoes/lib/rottenpotatoes/listing/movie.ex
defmodule Rottenpotatoes.Listing.Movie do
  use Ecto.Schema
  import Ecto.Changeset

  schema "movies" do
    field :description, :string
    field :rating, :string
    field :release_date, :date
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(movie, attrs) do
    movie
    |> cast(attrs, [:title, :description, :release_date, :rating])
    |> validate_required([:title, :release_date, :rating])
  end
end

phoenix/rottenpotatoes/lib/rottenpotatoes/repo.ex
defmodule Rottenpotatoes.Repo do
  use Ecto.Repo,
    otp_app: :rottenpotatoes,
    adapter: Ecto.Adapters.Postgres
end

phoenix/rottenpotatoes/lib/rottenpotatoes_web/controllers/movie_controller.ex
defmodule RottenpotatoesWeb.MovieController do
  use RottenpotatoesWeb, :controller

  alias Rottenpotatoes.{Repo, Listing.Movie}

  @all_ratings ~w[G PG PG-13 R]

  def index(conn, _params) do
    movies = Repo.all(Movie)
    render(
      conn, "index.html", 
      movies: movies, 
      ratings: @all_ratings, 
      selected_ratings: %{"G" => "on"}, 
      sort_by: ""
    )
  end
end

phoenix/rottenpotatoes/lib/rottenpotatoes_web/controllers/page_controller.ex
defmodule RottenpotatoesWeb.PageController do
  use RottenpotatoesWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

phoenix/rottenpotatoes/lib/rottenpotatoes_web/views/error_view.ex
defmodule RottenpotatoesWeb.ErrorView do
  use RottenpotatoesWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

phoenix/rottenpotatoes/lib/rottenpotatoes_web/views/layout_view.ex
defmodule RottenpotatoesWeb.LayoutView do
  use RottenpotatoesWeb, :view
end

phoenix/rottenpotatoes/lib/rottenpotatoes_web/views/movie_view.ex
defmodule RottenpotatoesWeb.MovieView do
  use RottenpotatoesWeb, :view
end

phoenix/rottenpotatoes/lib/rottenpotatoes_web/views/page_view.ex
defmodule RottenpotatoesWeb.PageView do
  use RottenpotatoesWeb, :view
end

phoenix/rottenpotatoes/lib/rottenpotatoes_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Rottenpotatoes · Phoenix Framework</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

phoenix/rottenpotatoes/lib/rottenpotatoes_web/templates/movie/index.html.eex
<h1>All movies</h1>

<form>
    <input type="hidden" name="sort_by" value="<%= @sort_by%>">
<%= for rating <- @ratings do %>
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="cb_<%= rating %>" <%= if @selected_ratings[rating], do: "checked", else: "" %> name="selected_ratings[<%= rating %>]" >
        <label class="form-check-label" for="cb_<%= rating %>"><%= rating %></label>
    </div>
<% end %>
    <button type="submit" class="btn btn-outline-primary btn-sm">Apply</button>
</form>

<table class="table table-striped">
  <thead>
    <tr>
      <th class=<%= if (@sort_by == "title"), do: "table-info", else: "" %> >
        <form>
            <input type="hidden" name="sort_by" value="title">
            <%= for {rating, _} <- @selected_ratings do %>
                <input type="hidden" name="selected_ratings[<%= rating %>]" value="on">
            <% end %>
            <button class="btn btn-link">Movie Title</button>
        </form>
      </th>
      <th>Rating</th>
      <th class=<%= if (@sort_by == "release_date"), do: "table-info", else: "" %> >
        <form>
            <input type="hidden" name="sort_by" value="release_date">
            <%= for {rating, _} <- @selected_ratings do %>
                <input type="hidden" name="selected_ratings[<%= rating %>]" value="on">
            <% end %>
            <button class="btn btn-link">Release Date</button>
        </form>
      </th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
<%= for movie <- @movies do %>
    <tr>
      <td><%= movie.title %></td>
      <td><%= movie.rating %></td>
      <td><%= movie.release_date %></td>
      <td><%= link "More about #{movie.title}", to: Routes.movie_path(@conn, :show, movie) %></td>
    </tr>
<% end %>
  </tbody>
</table>

phoenix/rottenpotatoes/lib/rottenpotatoes_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed or maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>